services:
  web:
    build:
      context: ../src/web
      dockerfile: ./Dockerfile
      args:
        APP_REQUIREMENT_FILE: '$APP_ENVIROMENT.txt'
        APP_IMAGE_FROM: 'python:3.12-bullseye'
    # command: python3 -m debugpy --listen 0.0.0.0:11102 manage.py runserver 0.0.0.0:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src/web/portfolio:/opt/portfolio/web
      - static_volume:/opt/portfolio/static
      - media_volume:/opt/portfolio/media
    ports:
      - '11102:11102' # debug py
      - '11101:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  front:
    build:
      context: ../src/front
      dockerfile: ./Dockerfile
    command: yarn dev
    volumes:
      - ../src/front/src:/home/app/
      - static_next_next:/home/app/.next/static
      - public_next_volume:/home/app/public
    depends_on:
      - web
  lb:
    build:
      context: ../src/lb
      dockerfile: ./Dockerfile
    ports:
      - 11100:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      - static_next_next:/home/app/next_static
      - public_next_volume:/home/app/next_public
    
volumes:
  postgres_volume:
  static_volume:
  media_volume:
  static_next_next:
  public_next_volume:
