services:
  front:
    build:
      context: ../src/front
      dockerfile: ./Dockerfile
    command: yarn dev
    env_file:
      - ./env_file/$APP_ENVIROMENT.env
    volumes:
      - ../src/front/next:/home/app/next/
  web:
    image: $APP_WEB_IMAGE
    build:
      context: ../src/web
      dockerfile: ./Dockerfile
      args:
        APP_REQUIREMENT_FILE: '$APP_ENVIROMENT.txt'
        APP_IMAGE_FROM: 'python:3.9-bullseye'
    command: python3 manage.py runserver
    depends_on:
      - db
    volumes:
      - static_volume:/opt/portfolio/static
      - media_volume:/opt/portfolio/media
  db:
    image: $APP_DB_IMAGE
    build:
      context: ../src/db
      dockerfile: ./Dockerfile
    env_file:
      - ./env_file/$APP_ENVIROMENT.env
    volumes:
      - postgres_volume:/var/lib/mysql
  lb:
    image: $APP_LB_IMAGE
    build:
      context: ../src/lb
      dockerfile: ./Dockerfile
    
volumes:
  postgres_volume:
  static_volume:
  media_volume:
