services:
  front:
    image: $APP_FRONT_IMAGE
    build:
      context: ../src/front
      dockerfile: ./Dockerfile
    command: yarn start
    env_file:
      - ./env_file/ci.env
    volumes:
      - static_next_next:/home/app/.next/static
      - public_next_volume:/home/app/public
  web:
    image: $APP_WEB_IMAGE
    build:
      context: ../src/web
      dockerfile: ./Dockerfile
      args:
        APP_REQUIREMENT_FILE: 'production.txt'
        APP_IMAGE_FROM: 'python:3.12-bullseye'
    command: gunicorn --bind 0.0.0.0:8000 -w 8 src.wsgi:application
    env_file:
      - ./env_file/ci.env
    depends_on:
      - db
    volumes:
      - static_volume:/opt/portfolio/static
      - media_volume:/opt/portfolio/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:16
    env_file:
      - ./env_file/ci.env
  lb:
    image: $APP_LB_IMAGE
    build:
      context: ../src/lb
      dockerfile: ./Dockerfile
    ports:
        - 11120:80
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      - static_next_next:/home/app/next_static
      - public_next_volume:/home/app/next_public
    
volumes:
  static_volume:
  media_volume:
  static_next_next:
  public_next_volume:

