# Stage 1: Build the Next.js app
FROM node:18-alpine AS builder

WORKDIR /app

# Install dependencies
COPY src/package.json /app/package.json
RUN yarn install

# Copy the Next.js app source code
COPY ./src /app/

# Expose the port Next.js listens on
EXPOSE 3000

# Run Next.js
CMD ["yarn", "start"]
